---
site_name: AWX Operator Helm Chart
site_url: https://awx-operator.readthedocs.io/
repo_url: https://github.com/ansible-community/awx-operator-helm
edit_uri: blob/devel/docs/
docs_dir: docs
strict: true
use_directory_urls: false

theme:
  name: "ansible"
  features:
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - helm-install-on-existing-cluster.md
  - contributing.md

exclude_docs:
  README.md

plugins:
  - autorefs
  - markdown-exec
  - material/search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 2
      permalink: true
