{{- $operatorControllerTemplate := (include "awx-operator.controller" $) | fromYaml }}
{{- $_ := mergeOverwrite $operatorControllerTemplate (index $.Values "operator-controller") }}

{{ $operatorControllerTemplate | toYaml }}
