---

name: CI

on:
  pull_request:
  push:

jobs:
  helm:
    runs-on: ubuntu-latest
    name: helm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Output Python info
        run: python --version && which python

      - name: Clone ansible/awx-operator
        run: python ./clone-awx-operator.py

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0

      - name: Build operator image and load into kind
        run: |
          IMG=awx-operator-ci make docker-build
          kind load docker-image --name chart-testing awx-operator-ci

      - name: Patch pull policy for tests
        run: |
          kustomize edit add patch --path ../testing/pull_policy/Never.yaml
        working-directory: config/default

      - name: Build and lint helm chart
        run: |
          IMG=awx-operator-ci make helm-chart
          helm lint ./charts/awx-operator

      - name: Install kubeval
        run: |
          mkdir tmp && cd tmp
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin
        working-directory: ./charts

      - name: Run kubeval
        run: |
          helm template -n awx awx-operator > tmp/test.yaml
          kubeval --strict --force-color --ignore-missing-schemas tmp/test.yaml
        working-directory: ./charts

      - name: Install helm chart
        run: |
          helm install --wait my-awx-operator --namespace awx --create-namespace ./charts/awx-operator
  nox-sessions:
    uses: ./.github/workflows/reusable-nox.yml
